workflows:
  ios-release-workflow:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: development
        bundle_identifier: kz.netcore.tms
    scripts:
      - script: keychain initialize
      - script: keychain add-certificates

      - script: xcode-project use-profiles

      - script: flutter pub get

      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --export-options-plist=test/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
